# Generated by Django 4.2.15 on 2024-09-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogArticles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
