# Generated by Django 4.2.15 on 2024-09-09 09:52

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogArticles', '0002_post_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Education', 'Education'), ('Crypto', 'Crypto')], default='Technology', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='post_title', unique=True),
        ),
    ]
