# Generated by Django 4.2.15 on 2024-09-10 05:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogArticles', '0003_alter_post_post_category_alter_post_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='post_title', unique=True),
        ),
    ]
